---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
filters:
  tag:Project: arm-capi-builder
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: role
hostnames:
  - ip-address
compose:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('../terraform/ssh-key.pem', true) }}"
